# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\7100u\ADdesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_File(object):
    def setupUi(self, File):
        File.setObjectName("File")
        File.resize(990, 692)
        File.setMinimumSize(QtCore.QSize(990, 680))
        self.BigWidget = QtWidgets.QWidget(File)
        self.BigWidget.setGeometry(QtCore.QRect(11, 11, 550, 660))
        self.BigWidget.setMinimumSize(QtCore.QSize(550, 660))
        self.BigWidget.setObjectName("BigWidget")
        self.widget = QtWidgets.QWidget(self.BigWidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 552, 661))
        self.widget.setObjectName("widget")
        self.vbox = QtWidgets.QVBoxLayout(self.widget)
        self.vbox.setContentsMargins(0, 0, 0, 0)
        self.vbox.setObjectName("vbox")
        self.Widget = QtWidgets.QWidget(self.widget)
        self.Widget.setMinimumSize(QtCore.QSize(550, 260))
        self.Widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Widget.setObjectName("Widget")
        self.lineEdit2 = QtWidgets.QLineEdit(self.Widget)
        self.lineEdit2.setGeometry(QtCore.QRect(210, 70, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setStyleSheet("font: 63 14pt \"Bookman Old Style\";\n"
"")
        self.lineEdit2.setObjectName("lineEdit2")
        self.label1 = QtWidgets.QLabel(self.Widget)
        self.label1.setGeometry(QtCore.QRect(11, 19, 201, 41))
        self.label1.setStyleSheet("font: 12pt \"서울남산체 B\";\n"
"background-color: rgb(226, 255, 208);")
        self.label1.setObjectName("label1")
        self.lineEdit1 = QtWidgets.QLineEdit(self.Widget)
        self.lineEdit1.setGeometry(QtCore.QRect(209, 19, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit1.setStyleSheet("font: 63 14pt \"Bookman Old Style\";\n"
"")
        self.lineEdit1.setFrame(True)
        self.lineEdit1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit1.setObjectName("lineEdit1")
        self.label2 = QtWidgets.QLabel(self.Widget)
        self.label2.setGeometry(QtCore.QRect(10, 70, 198, 41))
        self.label2.setStyleSheet("background-color: rgb(226, 255, 208);\n"
"font: 12pt \"서울남산체 B\";")
        self.label2.setObjectName("label2")
        self.pushButton = QtWidgets.QPushButton(self.Widget)
        self.pushButton.setGeometry(QtCore.QRect(440, 180, 101, 71))
        self.pushButton.setStyleSheet("font: 75 20pt \"Berlin Sans FB Demi\";\n"
"background-color: rgb(250, 250, 250);")
        self.pushButton.setObjectName("pushButton")
        self.sWidget = QtWidgets.QWidget(self.Widget)
        self.sWidget.setGeometry(QtCore.QRect(200, 120, 351, 51))
        self.sWidget.setStyleSheet("background-color: rgb(220, 255, 183);")
        self.sWidget.setObjectName("sWidget")
        self.ComBoxWidget = QtWidgets.QLabel(self.sWidget)
        self.ComBoxWidget.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.ComBoxWidget.setStyleSheet("background-color: rgb(220, 255, 183);")
        self.ComBoxWidget.setObjectName("ComBoxWidget")
        self.ComBox = QtWidgets.QComboBox(self.sWidget)
        self.ComBox.setGeometry(QtCore.QRect(130, 10, 211, 31))
        self.ComBox.setStyleSheet("\n"
"background-color: rgb(0, 170, 0);")
        self.ComBox.setObjectName("ComBox")
        self.ComBox.addItem("")
        self.ComBox.addItem("")
        self.ComBox.addItem("")
        self.vbox.addWidget(self.Widget)
        self.TextEdit = QtWidgets.QTextEdit(self.widget)
        self.TextEdit.setMinimumSize(QtCore.QSize(550, 380))
        self.TextEdit.setStyleSheet("gridline-color: rgb(255, 255, 255);")
        self.TextEdit.setAcceptRichText(True)
        self.TextEdit.setObjectName("TextEdit")
        self.vbox.addWidget(self.TextEdit)
        self.TabView = QtWidgets.QTableView(File)
        self.TabView.setGeometry(QtCore.QRect(568, 11, 400, 660))
        self.TabView.setMinimumSize(QtCore.QSize(400, 660))
        self.TabView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.TabView.setObjectName("TabView")
        self.TabView.horizontalHeader().setCascadingSectionResizes(False)
        self.widget1 = QtWidgets.QWidget(File)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.retranslateUi(File)
        QtCore.QMetaObject.connectSlotsByName(File)

    def retranslateUi(self, File):
        _translate = QtCore.QCoreApplication.translate
        File.setWindowTitle(_translate("File", "Form"))
        self.lineEdit2.setText(_translate("File", "C:\\users"))
        self.label1.setText(_translate("File", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0055ff;\">분류할 폴더 지정 =&gt;</span></p></body></html>"))
        self.lineEdit1.setText(_translate("File", "C:\\\\users\\dd"))
        self.label2.setText(_translate("File", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0055ff;\">정리될 폴더 지정 =&gt;</span></p></body></html>"))
        self.pushButton.setText(_translate("File", "OK"))
        self.ComBoxWidget.setText(_translate("File", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">분류 방법 :</span></p></body></html>"))
        self.ComBox.setItemText(0, _translate("File", "이름 분류"))
        self.ComBox.setItemText(1, _translate("File", "확장자 분류"))
        self.ComBox.setItemText(2, _translate("File", "날짜 분류"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    File = QtWidgets.QWidget()
    ui = Ui_File()
    ui.setupUi(File)
    File.show()
    sys.exit(app.exec_())
